import LocalizedStrings from "react-native-localization";

const stringsOfLanguages = new LocalizedStrings({
    en: {
      FunDoNotes: 'Fun Do Notes',
      Forgotpassword: 'Forgot Password?',
      createaccount: 'Do Not Have Any Account?',
      email: 'Email',
      password: 'Password',
      signin: 'Sign In',
      signingoogle: 'Sign In With Google',
      createanewccount: 'Create An Account',
      name: 'Name',
      confirmpass: 'Confirm Password',
      signup: 'Sign Up',
      setnewpass: 'Set New Password',
      oldpass: 'Old Password',
      submit: 'Submit',
      language_change: 'language change in Hindi',
      Bridgelabz: 'Bridgelabz',
      Search_your_Notes: 'Search your Notes',
      Logout: 'Logout',
      Notes: 'Notes',
      Reminders: 'Reminders',
      Labels: 'Labels',
      Edit: 'Edit',
      Create_new_label: 'Create new labels',
      Archive: 'Archive',
      Delete: 'Delete',
      settings: 'Settings',
      PINNED: 'PINNED',
      OTHERS: 'OTHERS',
      Charts: 'Charts',
    },
    Hindi: {
      FunDoNotes: 'फन डू नोट्स',
      forgotpassword: 'पासवर्ड भूल गए',
      createaccount: 'खाता बनाएं',
      email: 'ईमेल',
      password: 'पासवर्ड',
      signin: 'दाखिल करना',
      signingoogle: 'गूगल में साइन इन करें',
      Settings: 'समायोजन',
      language_change: 'अंग्रेजी में भाषा परिवर्तन करे !',
      Bridgelabz: 'ब्रिजलैब्ज',
      Search_your_Notes: 'अपने नोट्स खोजें',
      Logout: 'लॉग आउट',
      Notes: 'टिप्पणियाँ',
      Reminders: 'अनुस्मारक',
      Labels: 'लेबल',
      Edit: 'संपादन करना',
      Create_new_label: 'नया लेबल बनाएं',
      Archive: 'पुरालेख',
      Delete: 'मिटाना',
      settings: 'समायोजन',
      PINNED: 'पिन किए गए',
      OTHERS: 'अन्य',
      Charts: 'चार्ट',
    },
  });
  export default stringsOfLanguages;